#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d txt www sys doc msg aud vid

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#7ccdfd"
bspc config active_border_color "#7ccdfd"
bspc config focused_border_color "#f5748c"
bspc config presel-feedback_colour "#fc9d63"

bspc rule -a kitty desktop='txt' follow=on focus=on
bspc rule -a Google-chrome desktop='www' follow=on focus=on
bspc rule -a Firefox desktop='www' follow=on focus=on
bspc rule -a vlc desktop='vid' follow=on focus=on
bspc rule -a thunar desktop='sys' follow=on focus=on
bspc rule -a discord desktop='msg' follow=on focus=on
bspc rule -a soffice desktop='doc' follow=on focus=on
bspc rule -a beekeper-studio desktop='sys' follow=on focus=on
bspc rule -a ViberPC desktop='msg' follow=on focus=on


# Auto start
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --set-zoom-fill --random $HOME/Dev/walls-catppuccin-mocha &
dunst &
polybar &
