#!/usr/bin/env bash

#!/usr/bin/env bash

# Source modular functions
source "$(dirname "$0")/lib/common.sh"
source "$(dirname "$0")/lib/zsh.sh"
source "$(dirname "$0")/lib/mise.sh"
source "$(dirname "$0")/lib/yazi.sh"
source "$(dirname "$0")/lib/mac.sh"

mkdir -p $HOME/.local/bin

install_xcode
setup_homebrew
setup_oh_my_zsh
setup_zsh
setup_mise
setup_yabai_skhd
setup_yazi_plugins

# linking configs
echo -e "${CYAN}Linking stow${RESET}..."
stow --target=$HOME --adopt --verbose zsh zed yazi vscode tmux starship ssh nvim mise kitty git bin bat btop nb aerospace

echo -e "${GREEN}Installation and setup success${RESET}"
