#!/usr/bin/env bash

# Define color variables
RESET='\033[0m'
BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
RED='\033[0;31m'

DOTFILES=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
echo $DOTFILES;
# Function to link files with color output
link_file() {
    local src=$1
    local dest=$2
    local label=$3

    echo -e "${CYAN}Linking ${BOLD}$label${RESET}..."
    if [ -e "$dest" ]; then
        echo -e "${RED}Configuration for $label existed. Removing current config for ${BOLD}$label${RESET}..."
        rm -rf "$dest"
    fi
    ln -s "$src" "$dest"
    echo -e "${GREEN}Linked ${label}${RESET} to ${dest}"
}

link_file "$DOTFILES/kitty/*" "$HOME/.config/" "kitty"

link_file "$DOTFILES/tmux/.tmux.conf" "$HOME/.tmux.conf" "tmux"

mkdir -p $HOME/.local/bin

link_file "$DOTFILES/bin/tmux-sessionizer" "$HOME/.local/bin/tmux-sessionizer" "binaries"

link_file "$DOTFILES/nvim/*" "$HOME/.config/nvim" "nvim"

link_file "$DOTFILES/yabai/.yabairc" "$HOME/.yabairc" "yabai"

link_file "$DOTFILES/skhd/.skhdrc" "$HOME/.skhdrc" "skhd"

link_file "$DOTFILES/yazi/*" "$HOME/.config/yazi" "yazi"
link_file "$DOTFILES/mise/*" "$HOME/.config/mise" "mise"

echo -e "${CYAN}Installing ${BOLD}oh-my-zsh${RESET}..."
rm -rf $HOME/.oh-my-zsh
git clone https://github.com/ohmyzsh/ohmyzsh $HOME/.oh-my-zsh
export ZSH_PLUGIN_DIR="$HOME/.oh-my-zsh/plugins"
mkdir -p $ZSH_PLUGIN_DIR
git clone https://github.com/zsh-users/zsh-autocomplete.git $ZSH_PLUGIN_DIR/zsh-autocomplete
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $ZSH_PLUGIN_DIR/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions.git $ZSH_PLUGIN_DIR/zsh-autosuggestions
link_file "$DOTFILES/zsh/.zprofile" "$HOME/.zprofile" "zsh: .zprofile"
link_file "$DOTFILES/zsh/.zshrc" "$HOME/.zshrc" "zsh: .zshrc"
echo -e "${GREEN}zsh configured ${RESET}"

echo -e "${CYAN}Installing ${BOLD}xcode-select${RESET}..."
xcode-select --install
echo -e "${GREEN}Installed xcode-select ${RESET}"

echo -e "${CYAN}Installing ${BOLD}homebrew${RESET}..."
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
eval "$(/usr/local/bin/brew shellenv)"

echo -e "${CYAN}Installing ${BOLD}homebrew packages${RESET}..."
brew install wget curl zsh git neovim tmux lsd btop ripgrep fd bat jq kitty brave-browser zed font-monaspace starship docker docker-compose mise direnv yazi ffmpeg sevenzip poppler fzf zoxide resvg imagemagick font-symbols-only-nerd-font raycast

echo -e "${GREEN}Installed homebrew packages ${RESET}"

echo -e "${CYAN}Installing ${BOLD}homebrew skhd and yabai${RESET}..."
brew install koekeishiya/formulae/skhd
brew install koekeishiya/formulae/yabai
skhd --start-service
yabai --start-service
echo "$(whoami) ALL=(root) NOPASSWD: sha256:$(shasum -a 256 $(which yabai) | cut -d " " -f 1) $(which yabai) --load-sa" | sudo tee /private/etc/sudoers.d/yabai
echo -e "${GREEN}Installed skhd and yabai${RESET}"

echo -e "${CYAN}Setting up ${BOLD}mise${RESET}..."
eval "$(mise activate zsh)"
echo -e "${CYAN}Installing mise PHP dependencies ${RESET}..."
brew install autoconf automake bison freetype gd gettext icu4c krb5 libedit libiconv libjpeg libpng libxml2 libzip openssl pkg-config re2c zlib
export PATH="$(brew --prefix gettext)/bin:$PATH"
export PATH="$(brew --prefix icu4c)/bin:$PATH"
export PATH="$(brew --prefix openssl)/bin:$PATH"
export LDFLAGS="-L$(brew --prefix openssl)/lib"
export CPPFLAGS="-I$(brew --prefix openssl)/include"
echo -e "${CYAN}Installing mise tools${RESET}..."
mise install

echo -e "${GREEN}Installation success${RESET}"
