#!/usr/bin/env bash

# Define color variables
RESET='\033[0m'
BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
RED='\033[0;31m'

mkdir -p $HOME/.local/bin

# xcode
echo -e "${CYAN}Installing ${BOLD}xcode-select${RESET}..."
xcode-select --install
echo -e "${GREEN}Installed xcode-select ${RESET}"

# homebrew
echo -e "${CYAN}Installing ${BOLD}homebrew${RESET}..."
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
eval "$(/usr/local/bin/brew shellenv)"
echo -e "${CYAN}Installing ${BOLD}packages using brew bundle${RESET}..."
brew bundle
echo -e "${CYAN}Installing ${BOLD}homebrew skhd and yabai${RESET}..."
brew install koekeishiya/formulae/skhd
brew install koekeishiya/formulae/yabai
echo -e "${GREEN}Installed homebrew packages ${RESET}"


# zsh
echo -e "${CYAN}Installing ${BOLD}oh-my-zsh${RESET}..."
rm -rf $HOME/.oh-my-zsh
git clone https://github.com/ohmyzsh/ohmyzsh $HOME/.oh-my-zsh
export ZSH_PLUGIN_DIR="$HOME/.oh-my-zsh/plugins"
mkdir -p $ZSH_PLUGIN_DIR
git clone https://github.com/zsh-users/zsh-completions.git $ZSH_PLUGIN_DIR/zsh-completions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $ZSH_PLUGIN_DIR/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions.git $ZSH_PLUGIN_DIR/zsh-autosuggestions
echo -e "${GREEN}zsh configured ${RESET}"

# mise
echo -e "${CYAN}Setting up ${BOLD}mise${RESET}..."
eval "$(mise activate zsh)"
export PATH="$PATH"
export LDFLAGS="$LDFLAGS"
export CPPFLAGS="$CPPFLAGS"

# Add bin paths to PATH, and lib/include to LDFLAGS/CPPFLAGS
for formula in "${formulae[@]}"; do
  prefix=$(brew --prefix "$formula" 2>/dev/null)
  if [[ -d "$prefix" ]]; then
    [[ -d "$prefix/bin" ]] && export PATH="$prefix/bin:$PATH"
    [[ -d "$prefix/sbin" ]] && export PATH="$prefix/sbin:$PATH"
    [[ -d "$prefix/lib" ]] && export LDFLAGS="-L$prefix/lib $LDFLAGS"
    [[ -d "$prefix/include" ]] && export CPPFLAGS="-I$prefix/include $CPPFLAGS"
  fi
done

# Optionally deduplicate PATH, LDFLAGS, CPPFLAGS
PATH=$(awk -v RS=: -v ORS=: '!a[$1]++' <<<"$PATH" | sed 's/:$//')
LDFLAGS=$(xargs <<<"$LDFLAGS")
CPPFLAGS=$(xargs <<<"$CPPFLAGS")

echo -e "${CYAN}Installing mise tools${RESET}..."
mise install

# yabai and skhd
echo -e "${CYAN}Configure skhd and yabai${RESET}..."
echo "$(whoami) ALL=(root) NOPASSWD: sha256:$(shasum -a 256 $(which yabai) | cut -d " " -f 1) $(which yabai) --load-sa" | sudo tee /private/etc/sudoers.d/yabai
skhd --start-service
yabai --start-service

# linking configs
stow --target=$HOME --adopt --verbose zsh zed yazi vscode tmux shkd starship ssh nvim mise kitty git bin bat git btop yabai shkd

echo -e "${GREEN}Installation success${RESET}"
