#!/usr/bin/env bash

#!/usr/bin/env bash

# Source modular functions
source "$(dirname "$0")/lib/common.sh"
source "$(dirname "$0")/lib/zsh.sh"
source "$(dirname "$0")/lib/mise.sh"
source "$(dirname "$0")/lib/yazi.sh"
source "$(dirname "$0")/lib/arch.sh"

#############################
#                           #
#       Dependencies        #
#                           #
#############################

setup_directories
install_yay

# Install AUR packages using yay (AUR helper)
echo -e "${BLUE}Installing additional packages from AUR using yay...${RESET}"
aur_packages=(
    base
    linux
    linux-firmware
    bat
    betterlockscreen
    bluez
    bluez-tools
    brave-bin
    brightnessctl
    bspwm
    btop
    calc
    catppuccin-gtk-theme-mocha
    curl
    diff-so-fancy
    direnv
    docker
    docker-compose
    dunst
    fastfetch
    fd
    ffmpeg
    file
    fzf
    git
    imagemagick
    jq
    kitty
    kmonad
    less
    lsd
    lxappearance-gtk3
    ly
    maim
    maplemono-nf-cn-unhinted
    nb
    neovim
    networkmanager-dmenu
    nitrogen
    openssh
    papirus-folders-catppuccin-git
    papirus-icon-theme
    p7zip
    picom
    playerctl
    polybar
    poppler
    qmk
    qt5ct
    qt6ct
    resvg
    ripgrep
    rofi
    screenkey
    slop
    starship
    stow
    sxhkd
    tmux
    torrent-git
    ttf-nerd-fonts-symbols
    vlc
    visual-studio-code-bin
    wget
    wmctrl
    xclip
    xdotool
    xorg-xrandr
    yad
    yazi
    zed
    zoxide
    zsh
)

install_aur_packages "${aur_packages[@]}"

download_wallpapers
setup_tmux_tpm
setup_mise
configure_gtk
setup_zsh
setup_yazi_plugins
setup_dmenu
setup_docker
enable_services

echo -e "${CYAN}Linking stow${RESET}..."
stow --target=$HOME --adopt --verbose zsh zed yazi xinit vscode tmux sxhkd starship ssh screenkey rofi polybar picom nvim mise kitty git dunst bspwm bin bat gtk git btop nb

echo -e "${GREEN}${BOLD}Setup complete. All packages and configurations are installed.${RESET}"
