# Build-time / libs
brew "lima-additional-guestagents"

# CLI tools
brew "bat"
brew "btop"
brew "colima"
brew "curl"
brew "diff-so-fancy"
brew "direnv"
brew "docker"
brew "docker-compose"
brew "eza"
brew "fd"
brew "ffmpeg"
brew "file-formula"
brew "fzf"
brew "git"
brew "imagemagick"
brew "jq"
brew "lsd"
brew "mise"
brew "nb"
brew "neovim"
brew "pinentry"
brew "poppler"
brew "qmk"
brew "resvg"
brew "ripgrep"
brew "sevenzip"
brew "starship"
brew "stow"
brew "tmux"
brew "wget"
brew "yazi"
brew "zoxide"
brew "zsh"
brew "aws-vault"
brew "awscli"
brew "bash"
brew "container"
brew "gh"
brew "kubernetes-cli"
brew "lazydocker"
brew "luarocks"
brew "opencode"
brew "parallel"
brew "sshpass"
brew "stern"
brew "yq"

# Cask (GUI apps)
cask "kitty"
cask "vlc"
cask "visual-studio-code"
cask "zed"
cask "raycast"
cask "qmk-toolbox"
cask "nikitabobko/tap/aerospace"
cask "zen"
cask "tableplus"

# Fonts
cask "font-symbols-only-nerd-font"
cask "font-maple-mono-nf-cn"
