# Build-time / libs
brew "autoconf"
brew "automake"
brew "bison"
brew "freetype"
brew "gd"
brew "gettext"
brew "icu4c"
brew "krb5"
brew "libedit"
brew "libiconv"
brew "libjpeg"
brew "libpng"
brew "libxml2"
brew "libzip"
brew "openssl"
brew "pkg-config"
brew "re2c"
brew "zlib"

# CLI tools
brew "bat"
brew "btop"
brew "curl"
brew "diff-so-fancy"
brew "direnv"
brew "podman"
brew "docker-compose"
brew "fd"
brew "ffmpeg"
brew "file"
brew "fzf"
brew "git"
brew "imagemagick"
brew "jq"
brew "lsd"
brew "neovim"
brew "poppler"
brew "qmk/qmk/qmk"
brew "resvg"
brew "ripgrep"
brew "starship"
brew "stow"
brew "tmux"
brew "wget"
brew "yazi"
brew "zoxide"
brew "zsh"
brew "sevenzip"  # Note: Homebrew package name is p7zip, so replace if needed
brew "mise"      # Not found in core or casks, verify or remove
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"

# Cask (GUI apps)
cask "brave-browser"
cask "kitty"
cask "vlc"
cask "visual-studio-code"
cask "zed"
cask "raycast"
cask "qmk-toolbox"

# Fonts
cask "font-symbols-only-nerd-font"
cask "font-inter"
cask "font-monaspace"
cask "font-monaspace-nerd-font"
cask "font-maple-mono-nerd-font"
