#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd > /tmp/sxhkd.log 2>&1 &

bspc monitor -d msg doc txt sys www

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#7ccdfd"
bspc config active_border_color "#7ccdfd"
bspc config focused_border_color "#f5748c"
bspc config presel-feedback_colour "#fc9d63"

# Auto start
picom --config $HOME/.config/picom/picom.conf &
nitrogen --set-zoom-fill --random $HOME/Pictures/wallpapers &
dunst &
polybar -q main -c $HOME/.config/polybar/config.ini &
