vim.keymap.set('n', '<Esc>', '<cmd>nohlsearch<CR>', { desc = 'Highlight on search, but clear on pressing <Esc> in normal mode' })

vim.keymap.set('t', '<Esc><Esc>', '<C-\\><C-n>', { desc = 'Exit terminal mode' })
vim.keymap.set('n', '<C-h>', '<C-w><C-h>', { desc = 'Move focus to the left window', remap = true })
vim.keymap.set('n', '<C-l>', '<C-w><C-l>', { desc = 'Move focus to the right window', remap = true })
vim.keymap.set('n', '<C-j>', '<C-w><C-j>', { desc = 'Move focus to the lower window', remap = true })
vim.keymap.set('n', '<C-k>', '<C-w><C-k>', { desc = 'Move focus to the upper window', remap = true })
vim.keymap.set('n', 'k', "v:count == 0 ? 'gk' : 'k'", { expr = true, desc = 'Move cursor up' })
vim.keymap.set('n', 'j', "v:count == 0 ? 'gj' : 'j'", { expr = true, desc = 'Move cursor down' })
vim.keymap.set('n', '<C-M-h>', '<C-W>5<', { desc = 'Resize pane width to right' })
vim.keymap.set('n', '<C-M-l>', '<C-W>5>', { desc = 'Resize pane widht to left' })
vim.keymap.set('n', '<C-M-j>', '<C-W>-', { desc = 'Resize pane decrease height' })
vim.keymap.set('n', '<C-M-k>', '<C-W>+', { desc = 'Resize pane increase height' })
vim.keymap.set('v', '<', '<gv', { desc = 'Reselect visual selection after indenting to right' })
vim.keymap.set('v', '>', '>gv', { desc = 'Reselect visual selection after indenting to left' })
vim.keymap.set('v', 'y', 'myy`y', { desc = 'Maintain the cursor position when yanking a visual selection' })
vim.keymap.set('n', 'q:', ':q', { desc = 'Disable annoying command line typo' })
vim.keymap.set('v', 'p', '"_dP', { desc = 'Paste replace visual selection without copying it' })
vim.keymap.set('i', '<A-k>', '<Esc>:move .-2<CR>==gi', { desc = 'Move line up' })
vim.keymap.set('i', '<A-j>', '<Esc>:move .+1<CR>==gi', { desc = 'Move line down' })
vim.keymap.set('n', '<A-j>', ':move .+1<CR>==', { desc = 'Move line up' })
vim.keymap.set('n', '<A-k>', ':move .-2<CR>==', { desc = 'Move line down' })
vim.keymap.set('v', '<A-j>', ":move '>+1<CR>gv=gv", { desc = 'Move line up' })
vim.keymap.set('v', '<A-k>', ":move '<-2<CR>gv=gv", { desc = 'Move line down' })
vim.keymap.set('n', '<C-d>', '<C-d>zz', { desc = 'Center after jump down' })
vim.keymap.set('n', '<C-u>', '<C-u>zz', { desc = 'Center after jumo up' })
vim.keymap.set('n', 'J', 'mzJ`z', { desc = 'Fix line joins' })
vim.keymap.set('n', 'n', 'nzzzv', { desc = 'Center next highlight search' })
vim.keymap.set('n', 'N', 'Nzzzv', { desc = 'Center previous highlight search' })
-- vim: ts=2 sts=2 sw=2 et
